apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/EdgarEktibaryan/diplom.git
    targetRevision: refs/heads/main
    path: istio-configs