apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dist-traffic-app
spec:
  generators:
  - list:
      elements:
      - name: app-v1
        namespace: dist-traffic
        values_file: diplom-values-v1
      - name: app-v2
        namespace: dist-traffic
        values_file: diplom-values-v2
  template:
    metadata:
      name: 'dist-traffic-{{name}}'
    spec:
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: helm-chart/node-app
        repoURL: https://github.com/EdgarEktibaryan/diplom.git
        targetRevision: HEAD
        helm:
          releaseName: node-app
          valueFiles:
            - 'values.yaml'
            - '../../env/dist-traffic/{{values_file}}.yaml'