# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: kiali-ingress
#   namespace: istio-system
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: "kiali.edekt.com"
#     http:
#       paths:
#       - pathType: ImplementationSpecific
#         path: "/"
#         backend:
#           service:
#             name: kiali
#             port:
#               number: 20001