apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mtls-app
spec:
  generators:
  - list:
      elements:
      - name: app-v1
        namespace: app-ns1
        values_file: diplom-values-v1
      - name: app-v2
        namespace: app-ns1
        values_file: diplom-values-v2
  template:
    metadata:
      name: 'mtls-{{name}}'
    spec:
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: helm-chart/node-app
        repoURL: https://github.com/EdgarEktibaryan/diplom.git
        targetRevision: HEAD

        helm:
          releaseName: 'mtls-{{.name}}'
          values: |
            replicaCount: 2

            image:
              repository: "edgarektibaryan/public-node-{{name}}"
              pullPolicy: IfNotPresent
              tag: "25-04-16-1843"
            service:
              type: ClusterIP
              port: 80
            resources:
              limits:
                memory: "100Mi"
                cpu: "100m"
              requests:
                memory: "100Mi"
                cpu: "100m"
            ingress:
              enabled: true
              className: "nginx"
              hosts:
                - host: node-{{name}}.edekt.com
                  paths:
                    - path: /
                      pathType: Prefix