apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mtls-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: app-v1
        namespace: app-ns1
        values_file: diplom-values-v1
      - name: app-v2
        namespace: app-ns2
        values_file: diplom-values-v2
  template:
    metadata:
      name: 'mtls-{{name}}'
    spec:
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: helm-chart/node-app
        repoURL: https://github.com/EdgarEktibaryan/diplom.git
        helm:
          releaseName: 'mtls-{{name}}'
          valueFiles:
            - 'values.yaml'
            - '../../env/mtls/{{values_file}}.yaml'