
applications:
  - name: mtls-diplom-application
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/EdgarEktibaryan/diplom.git
      targetRevision: refs/heads/main
      path: argo-apps/mtls
      directory:
        recurse: false
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
    info:
    - name: url
      value: https://github.com/EdgarEktibaryan/diplom.git
  - name: dist-traffic-diplom-application
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/EdgarEktibaryan/diplom.git
      targetRevision: refs/heads/main
      path: argo-apps/dist-traffic
      directory:
        recurse: false
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
    info:
    - name: url
      value: https://github.com/EdgarEktibaryan/diplom.git