name: node-app-build-deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'     
        required: true
        type: choice
        options:
          - 'v1'
          - 'v2'
jobs:
  build-test:
    runs-on: ubuntu-latest
    outputs:
      AppVersion: ${{ steps.envs.outputs.AppVersion }}
      TagVERSION: ${{ steps.envs.outputs.TagVERSION }}
    steps:
      - name: Variables assignment
        run: |
          echo "AppVersion=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "TagVERSION=$(date +%y-%m-%d-%H%M)" >> $GITHUB_ENV
      - id: envs
        run: |
          echo "AppVersion=${{ env.AppVersion }}" >> $GITHUB_OUTPUT
          echo "TagVERSION=${{ env.TagVERSION }}" >> $GITHUB_OUTPUT
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Unit Test
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Environment preparation
        run: npm install
        working-directory: apps/app-${{ env.AppVersion }}
      - name: Running tests
        run: npm test
        working-directory: apps/app-${{ env.AppVersion }}
  containerise-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Variables set
        run: |
          echo "AppVersion=${{ needs.build-test.outputs.AppVersion }}" >> $GITHUB_ENV
          echo "TagVERSION=${{ needs.build-test.outputs.TagVERSION }}" >> $GITHUB_ENV
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Image build and push
        uses: docker/build-push-action@v6
        with:
          context: apps/app-${{ env.AppVersion }}
          push: true
          tags: ${{ vars.DOCKER_HUB_USER }}/public-node-app:${{ env.TagVERSION }}
  manifest-version-upadate:
    needs: [build-test, containerise-push]
    runs-on: ubuntu-latest
    steps:
      - name: Variables set
        run: |
          echo "TagVERSION=${{ needs.build-test.outputs.TagVERSION }}" >> $GITHUB_ENV
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Modify file (Example)
        run: |
          sed -i -r 's/tag:.*/tag:" ${{ env.TagVERSION }}"/' diplom-values.yaml
          cat diplom-values.yaml
        working-directory: ./env
      - name: Commit and push changes
        working-directory: ./env
        run: |
          git add .
          git commit -m "Version change to '"${{ env.TagVERSION }}"'"
          git push
        
